# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'EEBE_MapaKeUMKY.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *


class Ui_Planta_3(object):
    def setupUi(self, Planta_3):
        if Planta_3.objectName():
            Planta_3.setObjectName(u"Planta_3")
        Planta_3.resize(1527, 1043)
        self.centralwidget = QWidget(Planta_3)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 1551, 1051))
        self.intro = QWidget()
        self.intro.setObjectName(u"intro")
        self.logo = QLabel(self.intro)
        self.logo.setObjectName(u"logo")
        self.logo.setGeometry(QRect(60, 20, 471, 91))
        self.logo.setPixmap(QPixmap(u"logo_eebe.png"))
        self.logo.setScaledContents(True)
        self.foto = QLabel(self.intro)
        self.foto.setObjectName(u"foto")
        self.foto.setGeometry(QRect(700, 180, 811, 701))
        self.foto.setPixmap(QPixmap(u"EEBE.jpg"))
        self.foto.setScaledContents(True)
        self.plantas = QComboBox(self.intro)
        self.plantas.addItem("")
        self.plantas.addItem("")
        self.plantas.addItem("")
        self.plantas.addItem("")
        self.plantas.setObjectName(u"plantas")
        self.plantas.setGeometry(QRect(90, 610, 561, 61))
        font = QFont()
        font.setPointSize(11)
        self.plantas.setFont(font)
        self.edificios = QComboBox(self.intro)
        self.edificios.addItem("")
        self.edificios.addItem("")
        self.edificios.setObjectName(u"edificios")
        self.edificios.setGeometry(QRect(90, 500, 561, 61))
        self.edificios.setFont(font)
        self.explicacion = QLabel(self.intro)
        self.explicacion.setObjectName(u"explicacion")
        self.explicacion.setGeometry(QRect(90, 250, 561, 181))
        font1 = QFont()
        font1.setPointSize(6)
        self.explicacion.setFont(font1)
        self.explicacion.setAcceptDrops(True)
        self.explicacion.setScaledContents(False)
        self.explicacion.setWordWrap(True)
        self.titulo = QLabel(self.intro)
        self.titulo.setObjectName(u"titulo")
        self.titulo.setGeometry(QRect(570, 10, 881, 101))
        palette = QPalette()
        brush = QBrush(QColor(11, 145, 217, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(13, 145, 232, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush1)
        brush2 = QBrush(QColor(13, 145, 232, 128))
        brush2.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        brush3 = QBrush(QColor(120, 120, 120, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        brush4 = QBrush(QColor(0, 0, 0, 128))
        brush4.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush4)
#endif
        self.titulo.setPalette(palette)
        font2 = QFont()
        font2.setFamily(u"Arial Narrow")
        font2.setPointSize(18)
        font2.setBold(True)
        font2.setWeight(75)
        self.titulo.setFont(font2)
        self.titulo.setScaledContents(False)
        self.titulo.setAlignment(Qt.AlignCenter)
        self.titulo.setWordWrap(True)
        self.blank = QLabel(self.intro)
        self.blank.setObjectName(u"blank")
        self.blank.setGeometry(QRect(0, 0, 1521, 121))
        self.blank.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.blank2 = QLabel(self.intro)
        self.blank2.setObjectName(u"blank2")
        self.blank2.setGeometry(QRect(40, 180, 1011, 701))
        self.blank2.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.715909 rgba(255, 255, 255, 255), stop:0.948864 rgba(255, 255, 255, 0));")
        self.blank2.setLineWidth(1)
        self.stackedWidget.addWidget(self.intro)
        self.blank.raise_()
        self.logo.raise_()
        self.foto.raise_()
        self.titulo.raise_()
        self.blank2.raise_()
        self.explicacion.raise_()
        self.edificios.raise_()
        self.plantas.raise_()
        self.simulador = QWidget()
        self.simulador.setObjectName(u"simulador")
        self.tabWidget = QTabWidget(self.simulador)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1521, 1001))
        self.planta1 = QWidget()
        self.planta1.setObjectName(u"planta1")
        self.label = QLabel(self.planta1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 30, 1511, 941))
        self.label.setPixmap(QPixmap(u"P1.PNG"))
        self.label.setScaledContents(True)
        self.horizontalLayoutWidget_3 = QWidget(self.planta1)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(10, 0, 531, 80))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.dia1 = QComboBox(self.horizontalLayoutWidget_3)
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.addItem("")
        self.dia1.setObjectName(u"dia1")
        font3 = QFont()
        font3.setPointSize(8)
        self.dia1.setFont(font3)

        self.horizontalLayout_3.addWidget(self.dia1)

        self.mes1 = QComboBox(self.horizontalLayoutWidget_3)
        self.mes1.addItem("")
        self.mes1.addItem("")
        self.mes1.addItem("")
        self.mes1.addItem("")
        self.mes1.addItem("")
        self.mes1.addItem("")
        self.mes1.addItem("")
        self.mes1.addItem("")
        self.mes1.addItem("")
        self.mes1.addItem("")
        self.mes1.addItem("")
        self.mes1.addItem("")
        self.mes1.setObjectName(u"mes1")
        self.mes1.setFont(font3)

        self.horizontalLayout_3.addWidget(self.mes1)

        self.any1 = QComboBox(self.horizontalLayoutWidget_3)
        self.any1.addItem("")
        self.any1.addItem("")
        self.any1.setObjectName(u"any1")
        self.any1.setFont(font3)

        self.horizontalLayout_3.addWidget(self.any1)

        self.OK1 = QPushButton(self.horizontalLayoutWidget_3)
        self.OK1.setObjectName(u"OK1")
        self.OK1.setFont(font3)

        self.horizontalLayout_3.addWidget(self.OK1)

        self.A11 = QLabel(self.planta1)
        self.A11.setObjectName(u"A11")
        self.A11.setGeometry(QRect(200, 160, 121, 91))
        self.A11.setFont(font)
        self.A11.setStyleSheet(u"")
        self.A11.setAlignment(Qt.AlignCenter)
        self.A12 = QLabel(self.planta1)
        self.A12.setObjectName(u"A12")
        self.A12.setGeometry(QRect(130, 360, 111, 71))
        font4 = QFont()
        font4.setFamily(u"MS Shell Dlg 2")
        font4.setPointSize(11)
        self.A12.setFont(font4)
        self.A12.setAlignment(Qt.AlignCenter)
        self.A13 = QLabel(self.planta1)
        self.A13.setObjectName(u"A13")
        self.A13.setGeometry(QRect(120, 540, 101, 101))
        self.A13.setFont(font)
        self.A13.setAlignment(Qt.AlignCenter)
        self.A14 = QLabel(self.planta1)
        self.A14.setObjectName(u"A14")
        self.A14.setGeometry(QRect(190, 780, 131, 61))
        self.A14.setFont(font)
        self.A14.setAlignment(Qt.AlignCenter)
        self.A15 = QLabel(self.planta1)
        self.A15.setObjectName(u"A15")
        self.A15.setGeometry(QRect(500, 190, 91, 41))
        self.A15.setFont(font)
        self.A15.setAlignment(Qt.AlignCenter)
        self.A16 = QLabel(self.planta1)
        self.A16.setObjectName(u"A16")
        self.A16.setGeometry(QRect(420, 540, 91, 71))
        self.A16.setFont(font)
        self.A16.setAlignment(Qt.AlignCenter)
        self.A17 = QLabel(self.planta1)
        self.A17.setObjectName(u"A17")
        self.A17.setGeometry(QRect(470, 710, 101, 91))
        self.A17.setFont(font)
        self.A17.setAlignment(Qt.AlignCenter)
        self.A19 = QLabel(self.planta1)
        self.A19.setObjectName(u"A19")
        self.A19.setGeometry(QRect(950, 540, 111, 91))
        self.A19.setFont(font)
        self.A19.setAlignment(Qt.AlignCenter)
        self.A110 = QLabel(self.planta1)
        self.A110.setObjectName(u"A110")
        self.A110.setGeometry(QRect(950, 790, 61, 51))
        self.A110.setFont(font)
        self.A110.setAlignment(Qt.AlignCenter)
        self.A18 = QLabel(self.planta1)
        self.A18.setObjectName(u"A18")
        self.A18.setGeometry(QRect(1050, 100, 101, 81))
        self.A18.setFont(font)
        self.A18.setAlignment(Qt.AlignCenter)
        self.A111 = QLabel(self.planta1)
        self.A111.setObjectName(u"A111")
        self.A111.setGeometry(QRect(1310, 120, 141, 111))
        self.A111.setFont(font)
        self.A111.setAlignment(Qt.AlignCenter)
        self.A112 = QLabel(self.planta1)
        self.A112.setObjectName(u"A112")
        self.A112.setGeometry(QRect(1320, 330, 121, 131))
        self.A112.setFont(font)
        self.A112.setAlignment(Qt.AlignCenter)
        self.A113 = QLabel(self.planta1)
        self.A113.setObjectName(u"A113")
        self.A113.setGeometry(QRect(1320, 530, 111, 51))
        self.A113.setFont(font)
        self.A113.setAlignment(Qt.AlignCenter)
        self.A114 = QLabel(self.planta1)
        self.A114.setObjectName(u"A114")
        self.A114.setGeometry(QRect(1280, 640, 121, 91))
        self.A114.setFont(font)
        self.A114.setAlignment(Qt.AlignCenter)
        self.A115 = QLabel(self.planta1)
        self.A115.setObjectName(u"A115")
        self.A115.setGeometry(QRect(1210, 810, 131, 91))
        self.A115.setFont(font)
        self.A115.setAlignment(Qt.AlignCenter)
        self.colorA11 = QLabel(self.planta1)
        self.colorA11.setObjectName(u"colorA11")
        self.colorA11.setGeometry(QRect(200, 150, 121, 111))
        self.colorA11.setStyleSheet(u"")
        self.colorA12 = QLabel(self.planta1)
        self.colorA12.setObjectName(u"colorA12")
        self.colorA12.setGeometry(QRect(120, 340, 131, 111))
        self.colorA12.setStyleSheet(u"")
        self.colorA13 = QLabel(self.planta1)
        self.colorA13.setObjectName(u"colorA13")
        self.colorA13.setGeometry(QRect(100, 530, 141, 121))
        self.colorA13.setStyleSheet(u"")
        self.colorA14 = QLabel(self.planta1)
        self.colorA14.setObjectName(u"colorA14")
        self.colorA14.setGeometry(QRect(180, 750, 151, 121))
        self.colorA14.setStyleSheet(u"")
        self.colorA17 = QLabel(self.planta1)
        self.colorA17.setObjectName(u"colorA17")
        self.colorA17.setGeometry(QRect(450, 690, 131, 131))
        self.colorA17.setStyleSheet(u"")
        self.colorA16 = QLabel(self.planta1)
        self.colorA16.setObjectName(u"colorA16")
        self.colorA16.setGeometry(QRect(410, 530, 111, 91))
        self.colorA16.setStyleSheet(u"")
        self.colorA15 = QLabel(self.planta1)
        self.colorA15.setObjectName(u"colorA15")
        self.colorA15.setGeometry(QRect(500, 180, 91, 61))
        self.colorA15.setStyleSheet(u"")
        self.colorA18 = QLabel(self.planta1)
        self.colorA18.setObjectName(u"colorA18")
        self.colorA18.setGeometry(QRect(1040, 80, 121, 121))
        self.colorA18.setStyleSheet(u"")
        self.colorA111 = QLabel(self.planta1)
        self.colorA111.setObjectName(u"colorA111")
        self.colorA111.setGeometry(QRect(1300, 100, 151, 141))
        self.colorA111.setStyleSheet(u"")
        self.colorA112 = QLabel(self.planta1)
        self.colorA112.setObjectName(u"colorA112")
        self.colorA112.setGeometry(QRect(1310, 330, 141, 131))
        self.colorA112.setStyleSheet(u"")
        self.colorA113 = QLabel(self.planta1)
        self.colorA113.setObjectName(u"colorA113")
        self.colorA113.setGeometry(QRect(1310, 520, 131, 71))
        self.colorA113.setStyleSheet(u"")
        self.colorA114 = QLabel(self.planta1)
        self.colorA114.setObjectName(u"colorA114")
        self.colorA114.setGeometry(QRect(1260, 630, 151, 111))
        self.colorA114.setStyleSheet(u"")
        self.colorA115 = QLabel(self.planta1)
        self.colorA115.setObjectName(u"colorA115")
        self.colorA115.setGeometry(QRect(1190, 790, 161, 131))
        self.colorA115.setStyleSheet(u"")
        self.colorA19 = QLabel(self.planta1)
        self.colorA19.setObjectName(u"colorA19")
        self.colorA19.setGeometry(QRect(950, 530, 111, 111))
        self.colorA19.setStyleSheet(u"")
        self.colorA110 = QLabel(self.planta1)
        self.colorA110.setObjectName(u"colorA110")
        self.colorA110.setGeometry(QRect(940, 750, 81, 131))
        self.colorA110.setStyleSheet(u"")
        self.BACK1 = QPushButton(self.planta1)
        self.BACK1.setObjectName(u"BACK1")
        self.BACK1.setGeometry(QRect(1420, 0, 91, 31))
        self.BACK1.setFont(font3)
        self.tabWidget.addTab(self.planta1, "")
        self.label.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.colorA11.raise_()
        self.colorA12.raise_()
        self.colorA13.raise_()
        self.colorA14.raise_()
        self.colorA17.raise_()
        self.colorA16.raise_()
        self.colorA15.raise_()
        self.colorA18.raise_()
        self.colorA111.raise_()
        self.colorA112.raise_()
        self.colorA113.raise_()
        self.colorA114.raise_()
        self.colorA115.raise_()
        self.colorA19.raise_()
        self.colorA110.raise_()
        self.A11.raise_()
        self.A16.raise_()
        self.A15.raise_()
        self.A12.raise_()
        self.A13.raise_()
        self.A14.raise_()
        self.A17.raise_()
        self.A110.raise_()
        self.A19.raise_()
        self.A115.raise_()
        self.A114.raise_()
        self.A113.raise_()
        self.A112.raise_()
        self.A111.raise_()
        self.A18.raise_()
        self.BACK1.raise_()
        self.planta2 = QWidget()
        self.planta2.setObjectName(u"planta2")
        self.Planta2 = QLabel(self.planta2)
        self.Planta2.setObjectName(u"Planta2")
        self.Planta2.setGeometry(QRect(-150, 10, 1711, 951))
        self.Planta2.setPixmap(QPixmap(u"../P2.PNG"))
        self.Planta2.setScaledContents(True)
        self.horizontalLayoutWidget = QWidget(self.planta2)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(10, 0, 541, 81))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.dia2 = QComboBox(self.horizontalLayoutWidget)
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.addItem("")
        self.dia2.setObjectName(u"dia2")
        self.dia2.setFont(font3)

        self.horizontalLayout.addWidget(self.dia2)

        self.mes2 = QComboBox(self.horizontalLayoutWidget)
        self.mes2.addItem("")
        self.mes2.addItem("")
        self.mes2.addItem("")
        self.mes2.addItem("")
        self.mes2.addItem("")
        self.mes2.addItem("")
        self.mes2.addItem("")
        self.mes2.addItem("")
        self.mes2.addItem("")
        self.mes2.addItem("")
        self.mes2.addItem("")
        self.mes2.addItem("")
        self.mes2.setObjectName(u"mes2")
        self.mes2.setFont(font3)

        self.horizontalLayout.addWidget(self.mes2)

        self.any2 = QComboBox(self.horizontalLayoutWidget)
        self.any2.addItem("")
        self.any2.addItem("")
        self.any2.setObjectName(u"any2")
        self.any2.setFont(font3)

        self.horizontalLayout.addWidget(self.any2)

        self.OK2 = QPushButton(self.horizontalLayoutWidget)
        self.OK2.setObjectName(u"OK2")
        self.OK2.setFont(font3)

        self.horizontalLayout.addWidget(self.OK2)

        self.A21 = QLabel(self.planta2)
        self.A21.setObjectName(u"A21")
        self.A21.setGeometry(QRect(210, 150, 111, 101))
        self.A21.setFont(font)
        self.A21.setAlignment(Qt.AlignCenter)
        self.A22 = QLabel(self.planta2)
        self.A22.setObjectName(u"A22")
        self.A22.setGeometry(QRect(150, 340, 101, 81))
        self.A22.setFont(font)
        self.A22.setAlignment(Qt.AlignCenter)
        self.A23 = QLabel(self.planta2)
        self.A23.setObjectName(u"A23")
        self.A23.setGeometry(QRect(140, 530, 101, 81))
        self.A23.setFont(font)
        self.A23.setAlignment(Qt.AlignCenter)
        self.A24 = QLabel(self.planta2)
        self.A24.setObjectName(u"A24")
        self.A24.setGeometry(QRect(210, 740, 101, 71))
        self.A24.setFont(font)
        self.A24.setAlignment(Qt.AlignCenter)
        self.A27 = QLabel(self.planta2)
        self.A27.setObjectName(u"A27")
        self.A27.setGeometry(QRect(450, 670, 91, 101))
        self.A27.setFont(font)
        self.A27.setAlignment(Qt.AlignCenter)
        self.A210 = QLabel(self.planta2)
        self.A210.setObjectName(u"A210")
        self.A210.setGeometry(QRect(1000, 110, 81, 61))
        self.A210.setFont(font)
        self.A210.setAlignment(Qt.AlignCenter)
        self.A211 = QLabel(self.planta2)
        self.A211.setObjectName(u"A211")
        self.A211.setGeometry(QRect(1230, 110, 111, 111))
        self.A211.setFont(font)
        self.A211.setAlignment(Qt.AlignCenter)
        self.A212 = QLabel(self.planta2)
        self.A212.setObjectName(u"A212")
        self.A212.setGeometry(QRect(1240, 330, 101, 91))
        self.A212.setFont(font)
        self.A212.setAlignment(Qt.AlignCenter)
        self.A213 = QLabel(self.planta2)
        self.A213.setObjectName(u"A213")
        self.A213.setGeometry(QRect(1240, 500, 101, 51))
        self.A213.setFont(font)
        self.A213.setAlignment(Qt.AlignCenter)
        self.A214 = QLabel(self.planta2)
        self.A214.setObjectName(u"A214")
        self.A214.setGeometry(QRect(1190, 620, 111, 71))
        self.A214.setFont(font)
        self.A214.setAlignment(Qt.AlignCenter)
        self.A215 = QLabel(self.planta2)
        self.A215.setObjectName(u"A215")
        self.A215.setGeometry(QRect(1120, 760, 141, 101))
        self.A215.setFont(font)
        self.A215.setAlignment(Qt.AlignCenter)
        self.A28 = QLabel(self.planta2)
        self.A28.setObjectName(u"A28")
        self.A28.setGeometry(QRect(910, 530, 91, 71))
        self.A28.setFont(font)
        self.A28.setAlignment(Qt.AlignCenter)
        self.A29 = QLabel(self.planta2)
        self.A29.setObjectName(u"A29")
        self.A29.setGeometry(QRect(900, 740, 61, 51))
        self.A29.setFont(font)
        self.A29.setAlignment(Qt.AlignCenter)
        self.A26 = QLabel(self.planta2)
        self.A26.setObjectName(u"A26")
        self.A26.setGeometry(QRect(410, 510, 81, 71))
        self.A26.setFont(font)
        self.A26.setAlignment(Qt.AlignCenter)
        self.A25 = QLabel(self.planta2)
        self.A25.setObjectName(u"A25")
        self.A25.setGeometry(QRect(490, 190, 81, 41))
        self.A25.setFont(font)
        self.A25.setAlignment(Qt.AlignCenter)
        self.colorA21 = QLabel(self.planta2)
        self.colorA21.setObjectName(u"colorA21")
        self.colorA21.setGeometry(QRect(200, 150, 131, 111))
        self.colorA21.setStyleSheet(u"")
        self.colorA22 = QLabel(self.planta2)
        self.colorA22.setObjectName(u"colorA22")
        self.colorA22.setGeometry(QRect(140, 330, 121, 101))
        self.colorA22.setStyleSheet(u"")
        self.colorA23 = QLabel(self.planta2)
        self.colorA23.setObjectName(u"colorA23")
        self.colorA23.setGeometry(QRect(130, 520, 121, 111))
        self.colorA23.setStyleSheet(u"")
        self.colorA24 = QLabel(self.planta2)
        self.colorA24.setObjectName(u"colorA24")
        self.colorA24.setGeometry(QRect(190, 710, 141, 131))
        self.colorA24.setStyleSheet(u"")
        self.colorA26 = QLabel(self.planta2)
        self.colorA26.setObjectName(u"colorA26")
        self.colorA26.setGeometry(QRect(400, 500, 101, 91))
        self.colorA26.setStyleSheet(u"")
        self.colorA27 = QLabel(self.planta2)
        self.colorA27.setObjectName(u"colorA27")
        self.colorA27.setGeometry(QRect(440, 670, 111, 101))
        self.colorA27.setStyleSheet(u"")
        self.colorA25 = QLabel(self.planta2)
        self.colorA25.setObjectName(u"colorA25")
        self.colorA25.setGeometry(QRect(490, 180, 81, 61))
        self.colorA25.setStyleSheet(u"")
        self.colorA28 = QLabel(self.planta2)
        self.colorA28.setObjectName(u"colorA28")
        self.colorA28.setGeometry(QRect(900, 520, 101, 91))
        self.colorA28.setStyleSheet(u"")
        self.colorA29 = QLabel(self.planta2)
        self.colorA29.setObjectName(u"colorA29")
        self.colorA29.setGeometry(QRect(890, 720, 81, 91))
        self.colorA29.setStyleSheet(u"")
        self.colorA215 = QLabel(self.planta2)
        self.colorA215.setObjectName(u"colorA215")
        self.colorA215.setGeometry(QRect(1120, 750, 141, 121))
        self.colorA215.setStyleSheet(u"")
        self.colorA214 = QLabel(self.planta2)
        self.colorA214.setObjectName(u"colorA214")
        self.colorA214.setGeometry(QRect(1180, 600, 131, 111))
        self.colorA214.setStyleSheet(u"")
        self.colorA213 = QLabel(self.planta2)
        self.colorA213.setObjectName(u"colorA213")
        self.colorA213.setGeometry(QRect(1220, 490, 131, 71))
        self.colorA213.setStyleSheet(u"")
        self.colorA212 = QLabel(self.planta2)
        self.colorA212.setObjectName(u"colorA212")
        self.colorA212.setGeometry(QRect(1220, 310, 141, 131))
        self.colorA212.setStyleSheet(u"")
        self.colorA211 = QLabel(self.planta2)
        self.colorA211.setObjectName(u"colorA211")
        self.colorA211.setGeometry(QRect(1210, 100, 151, 131))
        self.colorA211.setStyleSheet(u"")
        self.colorA210 = QLabel(self.planta2)
        self.colorA210.setObjectName(u"colorA210")
        self.colorA210.setGeometry(QRect(990, 100, 101, 81))
        self.colorA210.setStyleSheet(u"")
        self.BACK2 = QPushButton(self.planta2)
        self.BACK2.setObjectName(u"BACK2")
        self.BACK2.setGeometry(QRect(1420, 0, 91, 31))
        self.BACK2.setFont(font3)
        self.tabWidget.addTab(self.planta2, "")
        self.Planta2.raise_()
        self.horizontalLayoutWidget.raise_()
        self.colorA21.raise_()
        self.colorA22.raise_()
        self.colorA23.raise_()
        self.colorA24.raise_()
        self.colorA26.raise_()
        self.colorA27.raise_()
        self.colorA25.raise_()
        self.colorA28.raise_()
        self.colorA29.raise_()
        self.colorA215.raise_()
        self.colorA214.raise_()
        self.colorA213.raise_()
        self.colorA212.raise_()
        self.colorA211.raise_()
        self.colorA210.raise_()
        self.A21.raise_()
        self.A22.raise_()
        self.A23.raise_()
        self.A24.raise_()
        self.A25.raise_()
        self.A26.raise_()
        self.A27.raise_()
        self.A28.raise_()
        self.A29.raise_()
        self.A215.raise_()
        self.A214.raise_()
        self.A213.raise_()
        self.A212.raise_()
        self.A211.raise_()
        self.A210.raise_()
        self.BACK2.raise_()
        self.planta3 = QWidget()
        self.planta3.setObjectName(u"planta3")
        self.Planta3 = QLabel(self.planta3)
        self.Planta3.setObjectName(u"Planta3")
        self.Planta3.setGeometry(QRect(20, 40, 1481, 931))
        self.Planta3.setPixmap(QPixmap(u"P3.PNG"))
        self.Planta3.setScaledContents(True)
        self.horizontalLayoutWidget_2 = QWidget(self.planta3)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(10, 0, 501, 61))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.dia3 = QComboBox(self.horizontalLayoutWidget_2)
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.addItem("")
        self.dia3.setObjectName(u"dia3")
        self.dia3.setFont(font3)

        self.horizontalLayout_2.addWidget(self.dia3)

        self.mes3 = QComboBox(self.horizontalLayoutWidget_2)
        self.mes3.addItem("")
        self.mes3.addItem("")
        self.mes3.addItem("")
        self.mes3.addItem("")
        self.mes3.addItem("")
        self.mes3.addItem("")
        self.mes3.addItem("")
        self.mes3.addItem("")
        self.mes3.addItem("")
        self.mes3.addItem("")
        self.mes3.addItem("")
        self.mes3.addItem("")
        self.mes3.setObjectName(u"mes3")
        self.mes3.setFont(font3)

        self.horizontalLayout_2.addWidget(self.mes3)

        self.any3 = QComboBox(self.horizontalLayoutWidget_2)
        self.any3.addItem("")
        self.any3.addItem("")
        self.any3.setObjectName(u"any3")
        self.any3.setFont(font3)

        self.horizontalLayout_2.addWidget(self.any3)

        self.OK3 = QPushButton(self.horizontalLayoutWidget_2)
        self.OK3.setObjectName(u"OK3")
        self.OK3.setFont(font3)

        self.horizontalLayout_2.addWidget(self.OK3)

        self.A31 = QLabel(self.planta3)
        self.A31.setObjectName(u"A31")
        self.A31.setGeometry(QRect(250, 120, 111, 51))
        font5 = QFont()
        font5.setPointSize(11)
        font5.setBold(False)
        font5.setWeight(50)
        self.A31.setFont(font5)
        self.A31.setAlignment(Qt.AlignCenter)
        self.A32 = QLabel(self.planta3)
        self.A32.setObjectName(u"A32")
        self.A32.setGeometry(QRect(210, 230, 101, 41))
        self.A32.setFont(font)
        self.A32.setAlignment(Qt.AlignCenter)
        self.A33 = QLabel(self.planta3)
        self.A33.setObjectName(u"A33")
        self.A33.setGeometry(QRect(160, 330, 101, 41))
        self.A33.setFont(font)
        self.A33.setAlignment(Qt.AlignCenter)
        self.A34 = QLabel(self.planta3)
        self.A34.setObjectName(u"A34")
        self.A34.setGeometry(QRect(130, 430, 101, 61))
        self.A34.setFont(font)
        self.A34.setAlignment(Qt.AlignCenter)
        self.A35 = QLabel(self.planta3)
        self.A35.setObjectName(u"A35")
        self.A35.setGeometry(QRect(520, 160, 71, 51))
        self.A35.setFont(font)
        self.A35.setAlignment(Qt.AlignCenter)
        self.A37 = QLabel(self.planta3)
        self.A37.setObjectName(u"A37")
        self.A37.setGeometry(QRect(410, 500, 81, 41))
        self.A37.setFont(font)
        self.A37.setAlignment(Qt.AlignCenter)
        self.A38 = QLabel(self.planta3)
        self.A38.setObjectName(u"A38")
        self.A38.setGeometry(QRect(1040, 140, 81, 71))
        self.A38.setFont(font)
        self.A38.setAlignment(Qt.AlignCenter)
        self.A39 = QLabel(self.planta3)
        self.A39.setObjectName(u"A39")
        self.A39.setGeometry(QRect(1300, 120, 111, 61))
        self.A39.setFont(font)
        self.A39.setAlignment(Qt.AlignCenter)
        self.A310 = QLabel(self.planta3)
        self.A310.setObjectName(u"A310")
        self.A310.setGeometry(QRect(1310, 260, 111, 61))
        self.A310.setFont(font)
        self.A310.setAlignment(Qt.AlignCenter)
        self.A311 = QLabel(self.planta3)
        self.A311.setObjectName(u"A311")
        self.A311.setGeometry(QRect(1310, 430, 111, 91))
        self.A311.setFont(font)
        self.A311.setAlignment(Qt.AlignCenter)
        self.A36 = QLabel(self.planta3)
        self.A36.setObjectName(u"A36")
        self.A36.setGeometry(QRect(460, 350, 71, 31))
        self.A36.setFont(font)
        self.A36.setAlignment(Qt.AlignCenter)
        self.colorA31 = QLabel(self.planta3)
        self.colorA31.setObjectName(u"colorA31")
        self.colorA31.setGeometry(QRect(240, 100, 131, 91))
        self.colorA31.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.colorA32 = QLabel(self.planta3)
        self.colorA32.setObjectName(u"colorA32")
        self.colorA32.setGeometry(QRect(200, 220, 111, 71))
        self.colorA32.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.193182 rgba(255, 152, 0, 255), stop:0.982955 rgba(255, 255, 255, 255));")
        self.colorA33 = QLabel(self.planta3)
        self.colorA33.setObjectName(u"colorA33")
        self.colorA33.setGeometry(QRect(150, 310, 111, 71))
        self.colorA33.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.193182 rgba(255, 239, 0, 255), stop:0.982955 rgba(255, 255, 255, 255));")
        self.colorA34 = QLabel(self.planta3)
        self.colorA34.setObjectName(u"colorA34")
        self.colorA34.setGeometry(QRect(120, 420, 121, 91))
        self.colorA34.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.193182 rgba(0, 255, 196, 255), stop:0.982955 rgba(255, 255, 255, 255));")
        self.colorA35 = QLabel(self.planta3)
        self.colorA35.setObjectName(u"colorA35")
        self.colorA35.setGeometry(QRect(510, 150, 91, 71))
        self.colorA35.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.255682 rgba(177, 0, 0, 255), stop:0.982955 rgba(255, 255, 255, 255));")
        self.colorA36 = QLabel(self.planta3)
        self.colorA36.setObjectName(u"colorA36")
        self.colorA36.setGeometry(QRect(450, 330, 91, 71))
        self.colorA36.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.193182 rgba(0, 54, 255, 255), stop:0.982955 rgba(255, 255, 255, 255));")
        self.colorA37 = QLabel(self.planta3)
        self.colorA37.setObjectName(u"colorA37")
        self.colorA37.setGeometry(QRect(400, 480, 101, 81))
        self.colorA37.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0.193182 rgba(0, 217, 255, 255), stop:0.982955 rgba(255, 255, 255, 255));")
        self.colorA38 = QLabel(self.planta3)
        self.colorA38.setObjectName(u"colorA38")
        self.colorA38.setGeometry(QRect(1030, 130, 101, 91))
        self.colorA38.setStyleSheet(u"")
        self.colorA39 = QLabel(self.planta3)
        self.colorA39.setObjectName(u"colorA39")
        self.colorA39.setGeometry(QRect(1290, 100, 131, 91))
        self.colorA39.setStyleSheet(u"")
        self.colorA310 = QLabel(self.planta3)
        self.colorA310.setObjectName(u"colorA310")
        self.colorA310.setGeometry(QRect(1300, 240, 131, 101))
        self.colorA310.setStyleSheet(u"")
        self.colorA311 = QLabel(self.planta3)
        self.colorA311.setObjectName(u"colorA311")
        self.colorA311.setGeometry(QRect(1290, 410, 141, 131))
        self.colorA311.setStyleSheet(u"")
        self.BACK3 = QPushButton(self.planta3)
        self.BACK3.setObjectName(u"BACK3")
        self.BACK3.setGeometry(QRect(1420, 0, 81, 31))
        self.BACK3.setFont(font3)
        self.tabWidget.addTab(self.planta3, "")
        self.Planta3.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.colorA31.raise_()
        self.colorA32.raise_()
        self.colorA33.raise_()
        self.colorA34.raise_()
        self.colorA35.raise_()
        self.colorA36.raise_()
        self.colorA37.raise_()
        self.colorA38.raise_()
        self.colorA39.raise_()
        self.colorA310.raise_()
        self.colorA311.raise_()
        self.A31.raise_()
        self.A32.raise_()
        self.A33.raise_()
        self.A34.raise_()
        self.A35.raise_()
        self.A37.raise_()
        self.A36.raise_()
        self.A38.raise_()
        self.A39.raise_()
        self.A310.raise_()
        self.A311.raise_()
        self.BACK3.raise_()
        self.stackedWidget.addWidget(self.simulador)
        Planta_3.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(Planta_3)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1527, 22))
        Planta_3.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(Planta_3)
        self.statusbar.setObjectName(u"statusbar")
        Planta_3.setStatusBar(self.statusbar)

        self.retranslateUi(Planta_3)

        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Planta_3)
    # setupUi

    def retranslateUi(self, Planta_3):
        Planta_3.setWindowTitle(QCoreApplication.translate("Planta_3", u"MainWindow", None))
        self.logo.setText("")
        self.foto.setText("")
        self.plantas.setItemText(0, QCoreApplication.translate("Planta_3", u"Tria una planta", None))
        self.plantas.setItemText(1, QCoreApplication.translate("Planta_3", u"Planta 1", None))
        self.plantas.setItemText(2, QCoreApplication.translate("Planta_3", u"Planta 2", None))
        self.plantas.setItemText(3, QCoreApplication.translate("Planta_3", u"Planta 3", None))

        self.edificios.setItemText(0, QCoreApplication.translate("Planta_3", u"Tria un edifici", None))
        self.edificios.setItemText(1, QCoreApplication.translate("Planta_3", u"EEBE UPC - Edifici A", None))

        self.explicacion.setText(QCoreApplication.translate("Planta_3", u"<html><head/><body><p align=\"justify\"><span style=\" font-size:11pt;\">Al simulador es poden consultar le temperatures en funci\u00f3 de les aules dels diferents edificis de l'Escola d'Enginyeria de Barcelona Est i en funci\u00f3 de la data escollida.</span></p></body></html>", None))
        self.titulo.setText(QCoreApplication.translate("Planta_3", u"SIMULADOR DE TEMPERATURAS EEBE UPC", None))
        self.blank.setText("")
        self.blank2.setText("")
        self.label.setText("")
        self.dia1.setItemText(0, QCoreApplication.translate("Planta_3", u"1", None))
        self.dia1.setItemText(1, QCoreApplication.translate("Planta_3", u"2", None))
        self.dia1.setItemText(2, QCoreApplication.translate("Planta_3", u"3", None))
        self.dia1.setItemText(3, QCoreApplication.translate("Planta_3", u"4", None))
        self.dia1.setItemText(4, QCoreApplication.translate("Planta_3", u"5", None))
        self.dia1.setItemText(5, QCoreApplication.translate("Planta_3", u"6", None))
        self.dia1.setItemText(6, QCoreApplication.translate("Planta_3", u"7", None))
        self.dia1.setItemText(7, QCoreApplication.translate("Planta_3", u"8", None))
        self.dia1.setItemText(8, QCoreApplication.translate("Planta_3", u"9", None))
        self.dia1.setItemText(9, QCoreApplication.translate("Planta_3", u"10", None))
        self.dia1.setItemText(10, QCoreApplication.translate("Planta_3", u"11", None))
        self.dia1.setItemText(11, QCoreApplication.translate("Planta_3", u"12", None))
        self.dia1.setItemText(12, QCoreApplication.translate("Planta_3", u"13", None))
        self.dia1.setItemText(13, QCoreApplication.translate("Planta_3", u"14", None))
        self.dia1.setItemText(14, QCoreApplication.translate("Planta_3", u"15", None))
        self.dia1.setItemText(15, QCoreApplication.translate("Planta_3", u"16", None))
        self.dia1.setItemText(16, QCoreApplication.translate("Planta_3", u"17", None))
        self.dia1.setItemText(17, QCoreApplication.translate("Planta_3", u"18", None))
        self.dia1.setItemText(18, QCoreApplication.translate("Planta_3", u"19", None))
        self.dia1.setItemText(19, QCoreApplication.translate("Planta_3", u"20", None))
        self.dia1.setItemText(20, QCoreApplication.translate("Planta_3", u"21", None))
        self.dia1.setItemText(21, QCoreApplication.translate("Planta_3", u"22", None))
        self.dia1.setItemText(22, QCoreApplication.translate("Planta_3", u"23", None))
        self.dia1.setItemText(23, QCoreApplication.translate("Planta_3", u"24", None))
        self.dia1.setItemText(24, QCoreApplication.translate("Planta_3", u"25", None))
        self.dia1.setItemText(25, QCoreApplication.translate("Planta_3", u"26", None))
        self.dia1.setItemText(26, QCoreApplication.translate("Planta_3", u"27", None))
        self.dia1.setItemText(27, QCoreApplication.translate("Planta_3", u"28", None))
        self.dia1.setItemText(28, QCoreApplication.translate("Planta_3", u"29", None))
        self.dia1.setItemText(29, QCoreApplication.translate("Planta_3", u"30", None))

        self.mes1.setItemText(0, QCoreApplication.translate("Planta_3", u"1", None))
        self.mes1.setItemText(1, QCoreApplication.translate("Planta_3", u"2", None))
        self.mes1.setItemText(2, QCoreApplication.translate("Planta_3", u"3", None))
        self.mes1.setItemText(3, QCoreApplication.translate("Planta_3", u"4", None))
        self.mes1.setItemText(4, QCoreApplication.translate("Planta_3", u"5", None))
        self.mes1.setItemText(5, QCoreApplication.translate("Planta_3", u"6", None))
        self.mes1.setItemText(6, QCoreApplication.translate("Planta_3", u"7", None))
        self.mes1.setItemText(7, QCoreApplication.translate("Planta_3", u"8", None))
        self.mes1.setItemText(8, QCoreApplication.translate("Planta_3", u"9", None))
        self.mes1.setItemText(9, QCoreApplication.translate("Planta_3", u"10", None))
        self.mes1.setItemText(10, QCoreApplication.translate("Planta_3", u"11", None))
        self.mes1.setItemText(11, QCoreApplication.translate("Planta_3", u"12", None))

        self.any1.setItemText(0, QCoreApplication.translate("Planta_3", u"2024", None))
        self.any1.setItemText(1, QCoreApplication.translate("Planta_3", u"2025", None))

        self.OK1.setText(QCoreApplication.translate("Planta_3", u"OK", None))
        self.A11.setText(QCoreApplication.translate("Planta_3", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.A12.setText(QCoreApplication.translate("Planta_3", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.A13.setText(QCoreApplication.translate("Planta_3", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.A14.setText(QCoreApplication.translate("Planta_3", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.A15.setText(QCoreApplication.translate("Planta_3", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.A16.setText(QCoreApplication.translate("Planta_3", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.A17.setText(QCoreApplication.translate("Planta_3", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.A19.setText("")
        self.A110.setText("")
        self.A18.setText(QCoreApplication.translate("Planta_3", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.A111.setText(QCoreApplication.translate("Planta_3", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.A112.setText(QCoreApplication.translate("Planta_3", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.A113.setText(QCoreApplication.translate("Planta_3", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.A114.setText(QCoreApplication.translate("Planta_3", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.A115.setText(QCoreApplication.translate("Planta_3", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.colorA11.setText("")
        self.colorA12.setText("")
        self.colorA13.setText("")
        self.colorA14.setText("")
        self.colorA17.setText("")
        self.colorA16.setText("")
        self.colorA15.setText("")
        self.colorA18.setText("")
        self.colorA111.setText("")
        self.colorA112.setText("")
        self.colorA113.setText("")
        self.colorA114.setText("")
        self.colorA115.setText("")
        self.colorA19.setText("")
        self.colorA110.setText("")
        self.BACK1.setText(QCoreApplication.translate("Planta_3", u"BACK", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.planta1), QCoreApplication.translate("Planta_3", u"Planta 1", None))
        self.Planta2.setText("")
        self.dia2.setItemText(0, QCoreApplication.translate("Planta_3", u"1", None))
        self.dia2.setItemText(1, QCoreApplication.translate("Planta_3", u"2", None))
        self.dia2.setItemText(2, QCoreApplication.translate("Planta_3", u"3", None))
        self.dia2.setItemText(3, QCoreApplication.translate("Planta_3", u"4", None))
        self.dia2.setItemText(4, QCoreApplication.translate("Planta_3", u"5", None))
        self.dia2.setItemText(5, QCoreApplication.translate("Planta_3", u"6", None))
        self.dia2.setItemText(6, QCoreApplication.translate("Planta_3", u"7", None))
        self.dia2.setItemText(7, QCoreApplication.translate("Planta_3", u"8", None))
        self.dia2.setItemText(8, QCoreApplication.translate("Planta_3", u"9", None))
        self.dia2.setItemText(9, QCoreApplication.translate("Planta_3", u"10", None))
        self.dia2.setItemText(10, QCoreApplication.translate("Planta_3", u"11", None))
        self.dia2.setItemText(11, QCoreApplication.translate("Planta_3", u"12", None))
        self.dia2.setItemText(12, QCoreApplication.translate("Planta_3", u"13", None))
        self.dia2.setItemText(13, QCoreApplication.translate("Planta_3", u"14", None))
        self.dia2.setItemText(14, QCoreApplication.translate("Planta_3", u"15", None))
        self.dia2.setItemText(15, QCoreApplication.translate("Planta_3", u"16", None))
        self.dia2.setItemText(16, QCoreApplication.translate("Planta_3", u"17", None))
        self.dia2.setItemText(17, QCoreApplication.translate("Planta_3", u"18", None))
        self.dia2.setItemText(18, QCoreApplication.translate("Planta_3", u"19", None))
        self.dia2.setItemText(19, QCoreApplication.translate("Planta_3", u"20", None))
        self.dia2.setItemText(20, QCoreApplication.translate("Planta_3", u"21", None))
        self.dia2.setItemText(21, QCoreApplication.translate("Planta_3", u"22", None))
        self.dia2.setItemText(22, QCoreApplication.translate("Planta_3", u"23", None))
        self.dia2.setItemText(23, QCoreApplication.translate("Planta_3", u"24", None))
        self.dia2.setItemText(24, QCoreApplication.translate("Planta_3", u"25", None))
        self.dia2.setItemText(25, QCoreApplication.translate("Planta_3", u"26", None))
        self.dia2.setItemText(26, QCoreApplication.translate("Planta_3", u"27", None))
        self.dia2.setItemText(27, QCoreApplication.translate("Planta_3", u"28", None))
        self.dia2.setItemText(28, QCoreApplication.translate("Planta_3", u"29", None))
        self.dia2.setItemText(29, QCoreApplication.translate("Planta_3", u"30", None))

        self.mes2.setItemText(0, QCoreApplication.translate("Planta_3", u"1", None))
        self.mes2.setItemText(1, QCoreApplication.translate("Planta_3", u"2", None))
        self.mes2.setItemText(2, QCoreApplication.translate("Planta_3", u"3", None))
        self.mes2.setItemText(3, QCoreApplication.translate("Planta_3", u"4", None))
        self.mes2.setItemText(4, QCoreApplication.translate("Planta_3", u"5", None))
        self.mes2.setItemText(5, QCoreApplication.translate("Planta_3", u"6", None))
        self.mes2.setItemText(6, QCoreApplication.translate("Planta_3", u"7", None))
        self.mes2.setItemText(7, QCoreApplication.translate("Planta_3", u"8", None))
        self.mes2.setItemText(8, QCoreApplication.translate("Planta_3", u"9", None))
        self.mes2.setItemText(9, QCoreApplication.translate("Planta_3", u"10", None))
        self.mes2.setItemText(10, QCoreApplication.translate("Planta_3", u"11", None))
        self.mes2.setItemText(11, QCoreApplication.translate("Planta_3", u"12", None))

        self.any2.setItemText(0, QCoreApplication.translate("Planta_3", u"2024", None))
        self.any2.setItemText(1, QCoreApplication.translate("Planta_3", u"2023", None))

        self.OK2.setText(QCoreApplication.translate("Planta_3", u"OK", None))
        self.A21.setText("")
        self.A22.setText("")
        self.A23.setText("")
        self.A24.setText("")
        self.A27.setText("")
        self.A210.setText("")
        self.A211.setText("")
        self.A212.setText("")
        self.A213.setText("")
        self.A214.setText("")
        self.A215.setText("")
        self.A28.setText("")
        self.A29.setText("")
        self.A26.setText("")
        self.A25.setText("")
        self.colorA21.setText("")
        self.colorA22.setText("")
        self.colorA23.setText("")
        self.colorA24.setText("")
        self.colorA26.setText("")
        self.colorA27.setText("")
        self.colorA25.setText("")
        self.colorA28.setText("")
        self.colorA29.setText("")
        self.colorA215.setText("")
        self.colorA214.setText("")
        self.colorA213.setText("")
        self.colorA212.setText("")
        self.colorA211.setText("")
        self.colorA210.setText("")
        self.BACK2.setText(QCoreApplication.translate("Planta_3", u"BACK", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.planta2), QCoreApplication.translate("Planta_3", u"Planta 2", None))
        self.Planta3.setText("")
        self.dia3.setItemText(0, QCoreApplication.translate("Planta_3", u"1", None))
        self.dia3.setItemText(1, QCoreApplication.translate("Planta_3", u"2", None))
        self.dia3.setItemText(2, QCoreApplication.translate("Planta_3", u"3", None))
        self.dia3.setItemText(3, QCoreApplication.translate("Planta_3", u"4", None))
        self.dia3.setItemText(4, QCoreApplication.translate("Planta_3", u"5", None))
        self.dia3.setItemText(5, QCoreApplication.translate("Planta_3", u"6", None))
        self.dia3.setItemText(6, QCoreApplication.translate("Planta_3", u"7", None))
        self.dia3.setItemText(7, QCoreApplication.translate("Planta_3", u"8", None))
        self.dia3.setItemText(8, QCoreApplication.translate("Planta_3", u"9", None))
        self.dia3.setItemText(9, QCoreApplication.translate("Planta_3", u"10", None))
        self.dia3.setItemText(10, QCoreApplication.translate("Planta_3", u"11", None))
        self.dia3.setItemText(11, QCoreApplication.translate("Planta_3", u"12", None))
        self.dia3.setItemText(12, QCoreApplication.translate("Planta_3", u"13", None))
        self.dia3.setItemText(13, QCoreApplication.translate("Planta_3", u"14", None))
        self.dia3.setItemText(14, QCoreApplication.translate("Planta_3", u"15", None))
        self.dia3.setItemText(15, QCoreApplication.translate("Planta_3", u"16", None))
        self.dia3.setItemText(16, QCoreApplication.translate("Planta_3", u"17", None))
        self.dia3.setItemText(17, QCoreApplication.translate("Planta_3", u"18", None))
        self.dia3.setItemText(18, QCoreApplication.translate("Planta_3", u"19", None))
        self.dia3.setItemText(19, QCoreApplication.translate("Planta_3", u"20", None))
        self.dia3.setItemText(20, QCoreApplication.translate("Planta_3", u"21", None))
        self.dia3.setItemText(21, QCoreApplication.translate("Planta_3", u"22", None))
        self.dia3.setItemText(22, QCoreApplication.translate("Planta_3", u"23", None))
        self.dia3.setItemText(23, QCoreApplication.translate("Planta_3", u"24", None))
        self.dia3.setItemText(24, QCoreApplication.translate("Planta_3", u"25", None))
        self.dia3.setItemText(25, QCoreApplication.translate("Planta_3", u"26", None))
        self.dia3.setItemText(26, QCoreApplication.translate("Planta_3", u"27", None))
        self.dia3.setItemText(27, QCoreApplication.translate("Planta_3", u"28", None))
        self.dia3.setItemText(28, QCoreApplication.translate("Planta_3", u"29", None))
        self.dia3.setItemText(29, QCoreApplication.translate("Planta_3", u"30", None))

        self.mes3.setItemText(0, QCoreApplication.translate("Planta_3", u"1", None))
        self.mes3.setItemText(1, QCoreApplication.translate("Planta_3", u"2", None))
        self.mes3.setItemText(2, QCoreApplication.translate("Planta_3", u"3", None))
        self.mes3.setItemText(3, QCoreApplication.translate("Planta_3", u"4", None))
        self.mes3.setItemText(4, QCoreApplication.translate("Planta_3", u"5", None))
        self.mes3.setItemText(5, QCoreApplication.translate("Planta_3", u"6", None))
        self.mes3.setItemText(6, QCoreApplication.translate("Planta_3", u"7", None))
        self.mes3.setItemText(7, QCoreApplication.translate("Planta_3", u"8", None))
        self.mes3.setItemText(8, QCoreApplication.translate("Planta_3", u"9", None))
        self.mes3.setItemText(9, QCoreApplication.translate("Planta_3", u"10", None))
        self.mes3.setItemText(10, QCoreApplication.translate("Planta_3", u"11", None))
        self.mes3.setItemText(11, QCoreApplication.translate("Planta_3", u"12", None))

        self.any3.setItemText(0, QCoreApplication.translate("Planta_3", u"2024", None))
        self.any3.setItemText(1, QCoreApplication.translate("Planta_3", u"2023", None))

        self.OK3.setText(QCoreApplication.translate("Planta_3", u"OK", None))
        self.A31.setText("")
        self.A32.setText("")
        self.A33.setText("")
        self.A34.setText("")
        self.A35.setText("")
        self.A37.setText("")
        self.A38.setText("")
        self.A39.setText("")
        self.A310.setText("")
        self.A311.setText("")
        self.A36.setText("")
        self.colorA31.setText("")
        self.colorA32.setText("")
        self.colorA33.setText("")
        self.colorA34.setText("")
        self.colorA35.setText("")
        self.colorA36.setText("")
        self.colorA37.setText("")
        self.colorA38.setText("")
        self.colorA39.setText("")
        self.colorA310.setText("")
        self.colorA311.setText("")
        self.BACK3.setText(QCoreApplication.translate("Planta_3", u"BACK", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.planta3), QCoreApplication.translate("Planta_3", u"Planta 3", None))
    # retranslateUi

