# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'EEBE_MapaKeUMKY.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *


class Ui_Planta_3(object):
    def setupUi(self, Planta_3):
        if Planta_3.objectName():
            Planta_3.setObjectName(u"Planta_3")
        Planta_3.resize(1494, 1033)
        self.centralwidget = QWidget(Planta_3)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Planta3 = QLabel(self.centralwidget)
        self.Planta3.setObjectName(u"Planta3")
        self.Planta3.setGeometry(QRect(-50, -50, 1631, 1171))
        self.Planta3.setMinimumSize(QSize(1451, 1061))
        self.Planta3.setPixmap(QPixmap(u"Q_ESPAI_EEBE/aules3.png"))
        self.Planta3.setScaledContents(True)
        self.aula1 = QLabel(self.centralwidget)
        self.aula1.setObjectName(u"aula1")
        self.aula1.setGeometry(QRect(210, 180, 191, 91))
        self.aula1.setPixmap(QPixmap(u"cuadrado blanco.png"))
        self.aula1.setScaledContents(True)
        self.dia = QComboBox(self.centralwidget)
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.setObjectName(u"dia")
        self.dia.setGeometry(QRect(60, 130, 131, 31))
        self.any = QComboBox(self.centralwidget)
        self.any.addItem("")
        self.any.addItem("")
        self.any.addItem("")
        self.any.setObjectName(u"any")
        self.any.setGeometry(QRect(340, 130, 131, 31))
        self.mes = QComboBox(self.centralwidget)
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.setObjectName(u"mes")
        self.mes.setGeometry(QRect(200, 130, 131, 31))
        self.A1 = QLabel(self.centralwidget)
        self.A1.setObjectName(u"A1")
        self.A1.setGeometry(QRect(40, 290, 221, 121))
        self.A2 = QLabel(self.centralwidget)
        self.A2.setObjectName(u"A2")
        self.A2.setGeometry(QRect(40, 470, 231, 121))
        self.A3 = QLabel(self.centralwidget)
        self.A3.setObjectName(u"A3")
        self.A3.setGeometry(QRect(40, 640, 231, 131))
        self.A4 = QLabel(self.centralwidget)
        self.A4.setObjectName(u"A4")
        self.A4.setGeometry(QRect(30, 810, 251, 141))
        self.A5 = QLabel(self.centralwidget)
        self.A5.setObjectName(u"A5")
        self.A5.setGeometry(QRect(390, 280, 151, 71))
        self.A6 = QLabel(self.centralwidget)
        self.A6.setObjectName(u"A6")
        self.A6.setGeometry(QRect(390, 390, 161, 51))
        self.A7 = QLabel(self.centralwidget)
        self.A7.setObjectName(u"A7")
        self.A7.setGeometry(QRect(460, 620, 141, 101))
        self.A8 = QLabel(self.centralwidget)
        self.A8.setObjectName(u"A8")
        self.A8.setGeometry(QRect(460, 770, 141, 191))
        self.A9 = QLabel(self.centralwidget)
        self.A9.setObjectName(u"A9")
        self.A9.setGeometry(QRect(920, 30, 191, 221))
        self.A10 = QLabel(self.centralwidget)
        self.A10.setObjectName(u"A10")
        self.A10.setGeometry(QRect(930, 340, 181, 151))
        self.A11 = QLabel(self.centralwidget)
        self.A11.setObjectName(u"A11")
        self.A11.setGeometry(QRect(780, 620, 201, 101))
        self.A12 = QLabel(self.centralwidget)
        self.A12.setObjectName(u"A12")
        self.A12.setGeometry(QRect(780, 760, 201, 201))
        self.A13 = QLabel(self.centralwidget)
        self.A13.setObjectName(u"A13")
        self.A13.setGeometry(QRect(1230, 30, 221, 241))
        self.A14 = QLabel(self.centralwidget)
        self.A14.setObjectName(u"A14")
        self.A14.setGeometry(QRect(1230, 300, 221, 131))
        self.A15 = QLabel(self.centralwidget)
        self.A15.setObjectName(u"A15")
        self.A15.setGeometry(QRect(1230, 470, 221, 51))
        self.A16 = QLabel(self.centralwidget)
        self.A16.setObjectName(u"A16")
        self.A16.setGeometry(QRect(1230, 550, 221, 141))
        self.A17 = QLabel(self.centralwidget)
        self.A17.setObjectName(u"A17")
        self.A17.setGeometry(QRect(1230, 720, 221, 241))
        Planta_3.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(Planta_3)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1494, 22))
        Planta_3.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(Planta_3)
        self.statusbar.setObjectName(u"statusbar")
        Planta_3.setStatusBar(self.statusbar)

        self.retranslateUi(Planta_3)
        self.dia.currentIndexChanged.connect(self.A1.setText)
        self.dia.currentIndexChanged.connect(self.A2.setText)
        self.dia.currentIndexChanged.connect(self.A3.setText)
        self.dia.currentIndexChanged.connect(self.A5.setText)
        self.dia.currentIndexChanged.connect(self.A6.setText)
        self.dia.currentIndexChanged.connect(self.A4.setText)
        self.dia.currentIndexChanged.connect(self.A7.setText)
        self.dia.currentIndexChanged.connect(self.A16.setText)
        self.dia.currentIndexChanged.connect(self.A8.setText)
        self.dia.currentIndexChanged.connect(self.A9.setText)
        self.dia.currentIndexChanged.connect(self.A10.setText)
        self.dia.currentIndexChanged.connect(self.A11.setText)
        self.dia.currentIndexChanged.connect(self.A12.setText)
        self.dia.currentIndexChanged.connect(self.A13.setText)
        self.dia.currentIndexChanged.connect(self.A14.setText)
        self.dia.currentIndexChanged.connect(self.A15.setText)
        self.dia.currentIndexChanged.connect(self.A17.setText)
        self.mes.currentIndexChanged.connect(self.A1.setText)

        QMetaObject.connectSlotsByName(Planta_3)
    # setupUi

    def retranslateUi(self, Planta_3):
        Planta_3.setWindowTitle(QCoreApplication.translate("Planta_3", u"MainWindow", None))
        self.Planta3.setText("")
        self.aula1.setText("")

        # Eliminar l'opció '-' i començar amb '1' als ComboBox
        self.dia.clear()
        self.dia.addItems([str(i) for i in range(1, 31)])

        self.any.clear()
        self.any.addItems(['2024', '2025'])  # Afegir els anys que es desitgi

        self.mes.clear()
        self.mes.addItems([str(i) for i in range(1, 13)])
    # retranslateUi

