# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'EEBE_MapaKeUMKY.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *

class Ui_Planta_3(object):
    def setupUi(self, Planta_3):
        if Planta_3.objectName():
            Planta_3.setObjectName(u"Planta_3")
        Planta_3.resize(1494, 1033)
        self.centralwidget = QWidget(Planta_3)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Planta3 = QLabel(self.centralwidget)
        self.Planta3.setObjectName(u"Planta3")
        self.Planta3.setGeometry(QRect(-50, -50, 1631, 1171))
        self.Planta3.setMinimumSize(QSize(1451, 1061))
        self.Planta3.setPixmap(QPixmap(u"aules3.png"))
        self.Planta3.setScaledContents(True)
        self.dia = QComboBox(self.centralwidget)
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.addItem("")
        self.dia.setObjectName(u"dia")
        self.dia.setGeometry(QRect(60, 130, 131, 31))
        self.any = QComboBox(self.centralwidget)
        self.any.addItem("")
        self.any.addItem("")
        self.any.setObjectName(u"any")
        self.any.setGeometry(QRect(340, 130, 131, 31))
        self.mes = QComboBox(self.centralwidget)
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.addItem("")
        self.mes.setObjectName(u"mes")
        self.mes.setGeometry(QRect(200, 130, 131, 31))
        self.A1 = QLabel(self.centralwidget)
        self.A1.setObjectName(u"A1")
        self.A1.setGeometry(QRect(40, 290, 221, 121))
        self.A2 = QLabel(self.centralwidget)
        self.A2.setObjectName(u"A2")
        self.A2.setGeometry(QRect(40, 470, 231, 121))
        self.A3 = QLabel(self.centralwidget)
        self.A3.setObjectName(u"A3")
        self.A3.setGeometry(QRect(40, 640, 231, 131))
        self.A4 = QLabel(self.centralwidget)
        self.A4.setObjectName(u"A4")
        self.A4.setGeometry(QRect(30, 810, 251, 141))
        self.A5 = QLabel(self.centralwidget)
        self.A5.setObjectName(u"A5")
        self.A5.setGeometry(QRect(390, 280, 151, 71))
        self.A6 = QLabel(self.centralwidget)
        self.A6.setObjectName(u"A6")
        self.A6.setGeometry(QRect(390, 390, 161, 51))
        self.A7 = QLabel(self.centralwidget)
        self.A7.setObjectName(u"A7")
        self.A7.setGeometry(QRect(460, 620, 141, 101))
        self.A8 = QLabel(self.centralwidget)
        self.A8.setObjectName(u"A8")
        self.A8.setGeometry(QRect(460, 770, 141, 191))
        self.A9 = QLabel(self.centralwidget)
        self.A9.setObjectName(u"A9")
        self.A9.setGeometry(QRect(920, 30, 191, 221))
        self.A10 = QLabel(self.centralwidget)
        self.A10.setObjectName(u"A10")
        self.A10.setGeometry(QRect(930, 340, 181, 151))
        self.A11 = QLabel(self.centralwidget)
        self.A11.setObjectName(u"A11")
        self.A11.setGeometry(QRect(780, 620, 201, 101))
        self.A12 = QLabel(self.centralwidget)
        self.A12.setObjectName(u"A12")
        self.A12.setGeometry(QRect(780, 760, 201, 201))
        self.A13 = QLabel(self.centralwidget)
        self.A13.setObjectName(u"A13")
        self.A13.setGeometry(QRect(1230, 30, 221, 241))
        self.A14 = QLabel(self.centralwidget)
        self.A14.setObjectName(u"A14")
        self.A14.setGeometry(QRect(1230, 300, 221, 131))
        self.A15 = QLabel(self.centralwidget)
        self.A15.setObjectName(u"A15")
        self.A15.setGeometry(QRect(1230, 470, 221, 51))
        self.A16 = QLabel(self.centralwidget)
        self.A16.setObjectName(u"A16")
        self.A16.setGeometry(QRect(1230, 550, 221, 141))
        self.A17 = QLabel(self.centralwidget)
        self.A17.setObjectName(u"A17")
        self.A17.setGeometry(QRect(1230, 720, 221, 241))
        self.OK = QPushButton(self.centralwidget)
        self.OK.setObjectName(u"OK")
        self.OK.setGeometry(QRect(490, 130, 61, 31))
        Planta_3.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(Planta_3)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1494, 22))
        Planta_3.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(Planta_3)
        self.statusbar.setObjectName(u"statusbar")
        Planta_3.setStatusBar(self.statusbar)

        self.retranslateUi(Planta_3)
        self.OK.clicked.connect(Planta_3.update_labels)
        #self.dia.currentIndexChanged.connect(Planta_3.date_changed)
        #self.mes.currentIndexChanged.connect(Planta_3.date_changed)
        #self.any.currentIndexChanged.connect(Planta_3.date_changed)

        QMetaObject.connectSlotsByName(Planta_3)
    # setupUi

    def retranslateUi(self, Planta_3):
        Planta_3.setWindowTitle(QCoreApplication.translate("Planta_3", u"MainWindow", None))
        self.Planta3.setText("")
        self.dia.setItemText(0, QCoreApplication.translate("Planta_3", u"1", None))
        self.dia.setItemText(1, QCoreApplication.translate("Planta_3", u"2", None))
        self.dia.setItemText(2, QCoreApplication.translate("Planta_3", u"3", None))
        self.dia.setItemText(3, QCoreApplication.translate("Planta_3", u"4", None))
        self.dia.setItemText(4, QCoreApplication.translate("Planta_3", u"5", None))
        self.dia.setItemText(5, QCoreApplication.translate("Planta_3", u"6", None))
        self.dia.setItemText(6, QCoreApplication.translate("Planta_3", u"7", None))
        self.dia.setItemText(7, QCoreApplication.translate("Planta_3", u"8", None))
        self.dia.setItemText(8, QCoreApplication.translate("Planta_3", u"9", None))
        self.dia.setItemText(9, QCoreApplication.translate("Planta_3", u"10", None))
        self.dia.setItemText(10, QCoreApplication.translate("Planta_3", u"11", None))
        self.dia.setItemText(11, QCoreApplication.translate("Planta_3", u"12", None))
        self.dia.setItemText(12, QCoreApplication.translate("Planta_3", u"13", None))
        self.dia.setItemText(13, QCoreApplication.translate("Planta_3", u"14", None))
        self.dia.setItemText(14, QCoreApplication.translate("Planta_3", u"15", None))
        self.dia.setItemText(15, QCoreApplication.translate("Planta_3", u"16", None))
        self.dia.setItemText(16, QCoreApplication.translate("Planta_3", u"17", None))
        self.dia.setItemText(17, QCoreApplication.translate("Planta_3", u"18", None))
        self.dia.setItemText(18, QCoreApplication.translate("Planta_3", u"19", None))
        self.dia.setItemText(19, QCoreApplication.translate("Planta_3", u"20", None))
        self.dia.setItemText(20, QCoreApplication.translate("Planta_3", u"21", None))
        self.dia.setItemText(21, QCoreApplication.translate("Planta_3", u"22", None))
        self.dia.setItemText(22, QCoreApplication.translate("Planta_3", u"23", None))
        self.dia.setItemText(23, QCoreApplication.translate("Planta_3", u"24", None))
        self.dia.setItemText(24, QCoreApplication.translate("Planta_3", u"25", None))
        self.dia.setItemText(25, QCoreApplication.translate("Planta_3", u"26", None))
        self.dia.setItemText(26, QCoreApplication.translate("Planta_3", u"27", None))
        self.dia.setItemText(27, QCoreApplication.translate("Planta_3", u"28", None))
        self.dia.setItemText(28, QCoreApplication.translate("Planta_3", u"29", None))
        self.dia.setItemText(29, QCoreApplication.translate("Planta_3", u"30", None))

        self.any.setItemText(0, QCoreApplication.translate("Planta_3", u"2024", None))
        self.any.setItemText(1, QCoreApplication.translate("Planta_3", u"2025", None))

        self.mes.setItemText(0, QCoreApplication.translate("Planta_3", u"1", None))
        self.mes.setItemText(1, QCoreApplication.translate("Planta_3", u"2", None))
        self.mes.setItemText(2, QCoreApplication.translate("Planta_3", u"3", None))
        self.mes.setItemText(3, QCoreApplication.translate("Planta_3", u"4", None))
        self.mes.setItemText(4, QCoreApplication.translate("Planta_3", u"5", None))
        self.mes.setItemText(5, QCoreApplication.translate("Planta_3", u"6", None))
        self.mes.setItemText(6, QCoreApplication.translate("Planta_3", u"7", None))
        self.mes.setItemText(7, QCoreApplication.translate("Planta_3", u"8", None))
        self.mes.setItemText(8, QCoreApplication.translate("Planta_3", u"9", None))
        self.mes.setItemText(9, QCoreApplication.translate("Planta_3", u"10", None))
        self.mes.setItemText(10, QCoreApplication.translate("Planta_3", u"11", None))
        self.mes.setItemText(11, QCoreApplication.translate("Planta_3", u"12", None))

        self.A1.setText("")
        self.A2.setText("")
        self.A3.setText("")
        self.A4.setText("")
        self.A5.setText("")
        self.A6.setText("")
        self.A7.setText("")
        self.A8.setText("")
        self.A9.setText("")
        self.A10.setText("")
        self.A11.setText("")
        self.A12.setText("")
        self.A13.setText("")
        self.A14.setText("")
        self.A15.setText("")
        self.A16.setText("")
        self.A17.setText(QCoreApplication.translate("Planta_3", u"TextLabel", None))
        self.OK.setText(QCoreApplication.translate("Planta_3", u"OK", None))
    # retranslateUi

